import type { NFT, BonusFeature, KeyBenefit } from "./types"
import { ViewIcon as View360 } from "lucide-react"

export const nftExamples: NFT[] = [
  {
    id: 1,
    title: "Cosmic Voyage",
    creator: "StarGazer",
    price: "0.5 ETH",
    type: "image",
    likes: 1200,
    comments: 89,
    shares: 45,
    bonusFeatures: 2,
    hasKeyBenefit: true,
    url: "/placeholder.svg?height=400&width=600",
    is360: true,
  },
  {
    id: 2,
    title: "Digital Dreams",
    creator: "CyberArtist",
    price: "0.7 ETH",
    type: "video",
    likes: 980,
    comments: 120,
    shares: 67,
    bonusFeatures: 1,
    hasKeyBenefit: false,
    url: "/placeholder.svg?height=400&width=600",
    is360: false,
  },
  {
    id: 3,
    title: "Neon Nights",
    creator: "GlowMaster",
    price: "0.6 ETH",
    type: "image",
    likes: 1500,
    comments: 210,
    shares: 98,
    bonusFeatures: 2,
    hasKeyBenefit: true,
    url: "/placeholder.svg?height=400&width=600",
    is360: true,
  },
  {
    id: 4,
    title: "Quantum Quasar",
    creator: "SpaceWizard",
    price: "0.8 ETH",
    type: "video",
    likes: 2200,
    comments: 180,
    shares: 120,
    bonusFeatures: 3,
    hasKeyBenefit: true,
    url: "/placeholder.svg?height=400&width=600",
    is360: true,
  },
  {
    id: 5,
    title: "Ethereal Whispers",
    creator: "DreamWeaver",
    price: "0.4 ETH",
    type: "image",
    likes: 950,
    comments: 78,
    shares: 34,
    bonusFeatures: 1,
    hasKeyBenefit: false,
    url: "/placeholder.svg?height=400&width=600",
    is360: false,
  },
  {
    id: 6,
    title: "Cybernetic Symphony",
    creator: "NeonMaster",
    price: "0.9 ETH",
    type: "video",
    likes: 2800,
    comments: 230,
    shares: 180,
    bonusFeatures: 3,
    hasKeyBenefit: true,
    url: "/placeholder.svg?height=400&width=600",
    is360: true,
  },
  {
    id: 7,
    title: "Galactic Bloom",
    creator: "StarDust",
    price: "0.6 ETH",
    type: "image",
    likes: 1700,
    comments: 145,
    shares: 90,
    bonusFeatures: 2,
    hasKeyBenefit: true,
    url: "/placeholder.svg?height=400&width=600",
    is360: false,
  },
  {
    id: 8,
    title: "Quantum Echoes",
    creator: "WaveRider",
    price: "0.75 ETH",
    type: "video",
    likes: 2100,
    comments: 190,
    shares: 110,
    bonusFeatures: 2,
    hasKeyBenefit: false,
    url: "/placeholder.svg?height=400&width=600",
    is360: true,
  },
]

export const bonusFeatures: BonusFeature[] = [
  { title: "Exclusive Access", description: "Gain early access to new NFT drops and collections." },
  { title: "Community Perks", description: "Enjoy special benefits and rewards within our community." },
  { title: "Creator Interaction", description: "Direct communication channel with the NFT creator." },
  { title: "360° Image Viewing", description: "Immersive 360° viewing experience for image NFTs.", icon: View360 },
  {
    title: "360° Video Playback",
    description: "Full 360° video playback support for an immersive experience.",
    icon: View360,
  },
]

export const keyBenefit: KeyBenefit = {
  title: "Lifetime Membership",
  description: "Enjoy exclusive benefits for life as a key holder.",
}

export const videoNFTs = nftExamples.filter((nft) => nft.type === "video")

